### ISSUE TITLE
No package MariaDB-devel available on CentOS 8

### ISSUE THREAD

**Issue by platix** [apisnetworks/apnscp#34] opened 2020-05-11 02:59 UTC
When setup with curl https://raw.githubusercontent.com/apisnetworks/apnscp-bootstrapper/master/bootstrap.sh | bash -s - -s has_low_memory=true -s use_robust_dns='true' -s dns_default_provider='powerdns' -s ftp_enabled='false' -s mail_enabled='false'

On CentOS 8, this error is droped.

fatal: [localhost]: FAILED! => {"attempts": 1, "changed": false, "failures": ["No package MariaDB-devel available.", "No package MariaDB-server available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}

The bug is reported in https://jira.mariadb.org/browse/MDEV-20673

This is fixed changing the mariadb repo file to this:
[mariadb]
name = MariaDB Server
baseurl = https://downloads.mariadb.com/MariaDB/mariadb-10.4/yum/rhel/$releasever/$basearch
gpgkey = file:///etc/pki/rpm-gpg/MariaDB-Server-GPG-KEY
gpgcheck = 1
enabled = 1
module_hotfixes = 1

**Comment by msaladna** [comment] 2020-05-11 03:14
Who's your VPS vendor? 

It could be caused by a "mariadb" AppStream being preconfigured on the server. `module_hotfixes` might fix it but if it's AppStream it's best to disable it permanently as ApisCP delivery supersedes it.

If I run through a test install using those parameters via /var/log/messages it appears to have installed OK on a Vultr 2 GB:

```
May 11 03:06:38 vultrguest bash[1374]: TASK [packages/install : Install packages] *************************************
May 11 03:06:38 vultrguest python3.6(mitogen:root@vultrguest:1385)[2695]: ansible-dnf Invoked with lock_timeout=300 state=installed name=['MariaDB-client', 'MariaDB-common', 'MariaDB-devel', 'MariaDB-server', 'MariaDB-shared'] skip_broken=True disablerepo=['*'] enablerepo=['mariadb', 'BaseOS'] allow_downgrade=False autoremove=False bugfix=False disable_gpg_check=False disable_plugin=[] download_only=False enable_plugin=[] exclude=[] installroot=/ install_repoquery=True install_weak_deps=True security=False update_cache=False update_only=False validate_certs=True conf_file=None disable_excludes=None download_dir=None list=None releasever=None
```

But likewise there's no "mariadb.module" present in /etc/dnf/modules.d,
```
[root@vultrguest yum.repos.d]# ll /etc/dnf/modules.d
total 48
-rw-r--r--. 1 root root 76 May  9 01:50 container-tools.module
-rw-r--r--  1 root root 66 May 11 03:07 go-toolset.module
-rw-r--r--  1 root root 52 May 11 03:06 httpd.module
-rw-r--r--  1 root root 87 May 11 03:07 javapackages-runtime.module
-rw-r--r--  1 root root 62 May 11 03:07 mercurial.module
-rw-r--r--  1 root root 48 May 11 03:06 php.module
-rw-r--r--  1 root root 60 May 11 03:07 python27.module
-rw-r--r--. 1 root root 60 May  9 01:57 python36.module
-rw-r--r--  1 root root 52 May 11 03:09 redis.module
-rw-r--r--. 1 root root 80 May  9 01:50 satellite-5-client.module
-rw-r--r--  1 root root 65 May 11 03:07 subversion.module
-rw-r--r--. 1 root root 53 May  9 01:50 virt.module
```

**Comment by msaladna** [comment] 2020-05-11 06:18
Resolved via lithiumhosting/apnscp-powerdns@81dfb0bb.

PowerDNS official package requires `libmysqlclient.so.21(libmysqlclient_21.0)(64bit)` (MySQL 8+) whereas EPEL has a weaker requirement, `libmariadb.so.3(libmysqlclient_18)(64bit)` supporting both MySQL 5.5+ and MariaDB 10.3+. Workaround for now if using MySQL as the database driver is require PowerDNS 4.3 released in April from EPEL.

Notes [updated](https://docs.apiscp.com/admin/dns/PowerDNS/#nameserver-installation) as well.

Thank you for the bug report!

**Closed as completed by msaladna** 2020-05-11 06:18 UTC

**Comment by platix** [comment] 2020-05-12 05:10
Thank you very much for the fix.
This error occurred because I installed powerdns before ApisCP.

After redoing a clean install first installing ApisCP, the error with the official powerdns repo came out.

For dns server only installations, it would be nice to add a parameter in the installer like dns_only or create a section in the documentation explaining how to do it exclusively and easyly, because I did not find anything clear and with these new types of licenses I consider it appropriate because the command I used I found it on the discord channel after reviewing the official documentation.

**Comment by msaladna** [comment] 2020-05-13 04:03
Ask and you shall receive, [has_dns_only=True](https://gitlab.com/apisnetworks/apnscp/-/commit/334f4dd766ced390044ecdb51959ceb48c688449#1126a27195f9fdd7d3e9f3dfbb8cd7f3ec96fd0f_41_44) is a new option that will disable non-essential features as of 3.1.42 and set default DNS provider to PowerDNS.

`cpcmd scope:set cp.bootstrapper has_dns_only true` will set this permanently.
